services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "p4ssw0rD" 
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mssql-server
    depends_on:
      - mssql-server

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  ecommerce-magazzino:
    image: ghcr.io/akille-21/esameecommerce/ecommerce-magazzino:latest
    container_name: ecommerce-magazzino
    pull_policy: always
    ports:
      - "5001:8080" 
    depends_on:
      mssql-server:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - ConnectionStrings__MagazzinoDbContext=Server=mssql-server;Database=MagazzinoDb;User Id=sa;Password=p4ssw0rD;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__ConsumerClient__BootstrapServers=kafka:29092
      - Kafka__ConsumerClient__GroupId=gruppo-magazzino-aggiornamento
      - Kafka__ConsumerClient__AutoOffsetReset=Earliest

  ecommerce-ordini:
    image: ghcr.io/akille-21/esameecommerce/ecommerce-ordini:latest
    container_name: ecommerce-ordini
    pull_policy: always
    restart: on-failure
    build:
      context: ../
      dockerfile: microservizi/Ecommerce.Ordini/Ecommerce.Ordini.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrdiniDbContext=Server=mssql-server;Database=OrdiniDb;User Id=sa;Password=p4ssw0rD;TrustServerCertificate=True;
      - Kafka__ProducerClient__BootstrapServers=kafka:29092
      - MagazzinoClientHttp__BaseAddress=http://ecommerce-magazzino:8080/
    ports:
      - "5002:8080"
    depends_on:
      mssql-server:
        condition: service_started
      kafka:
        condition: service_healthy
      ecommerce-magazzino:
        condition: service_started
    networks:
      - default

  ecommerce-pagamenti:
    image: ghcr.io/akille-21/esameecommerce/ecommerce-pagamenti:latest
    container_name: ecommerce-pagamenti
    pull_policy: always
    restart: on-failure
    build:
      context: ../
      dockerfile: microservizi/Ecommerce.Pagamenti/Ecommerce.Pagamenti.Api/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      mssql-server:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - ConnectionStrings__PagamentiDbContext=Server=mssql-server;Database=PagamentiDb;User Id=sa;Password=p4ssw0rD;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__ConsumerClient__BootstrapServers=kafka:29092
      - Kafka__ConsumerClient__GroupId=gruppo-pagamenti
      - Kafka__ConsumerClient__AutoOffsetReset=Earliest
      - Kafka__ProducerClient__BootstrapServers=kafka:29092

volumes:
  sqlvolume: